-- Numeric Functions

SELECT ROUND(5.73) -- WE GET 6

SELECT ROUND(5.7345, 2) -- WE GET 5.73

SELECT TRUNCATE(5.7345, 2)

SELECT CEILING(5.7) -- 6
SELECT CEILING(5.2) -- 6

SELECT FLOOR(5.2) -- 5

SELECT ABS(-5.2) -- 5.2

SELECT RAND() -- GENERATE BETWEEN 0 AND 1

-- GO TO GOOGLE AND SEARCH MYSQL NUMERIC FUNCTIONS TO SEE FULL ALL THE FUNCTIONS
