-- Date Functions in MySQL

SELECT NOW(), CURDATE(), CURTIME() -- current date and time - current date - current time 
SELECT YEAR(NOW()) -- EXTRACT YEAR
SELECT MONTH(NOW()) -- EXTRACT MONTH
SELECT DAY(NOW()) -- EXTRACT DAY
SELECT HOUR(NOW()) -- EXTRACT HOUR
SELECT MINUTE(NOW()) -- EXTRACT MINUTE
SELECT SECOND(NOW()) -- EXTRACT SECOND

-- THE ABOVE RETURNS INT VALUES

SELECT DAYNAME(NOW())
SELECT MONTHNAME(NOW())

SELECT EXTRACT(DAY FROM NOW())
SELECT EXTRACT(YEAR FROM NOW())
